# Created by Crt Vavros, copyright © 2022 ZeroPass. All rights reserved.
name: dmrtd
description: Dart implementation of ICAO Doc 9303 MRTD, created by ZeroPass

version: 2.0.0

environment:
  sdk: ^3.6.0

dependencies:
  archive: ^4.0.7
  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.7
  expandable: ^5.0.1
  fixnum: ^1.1.1
  flutter_nfc_kit: ^3.6.1
    #git:
    #  url: https://github.com/ZeroPass/flutter_nfc_kit.git
  logging: ^1.3.0
  meta: ^1.17.0
  tripledes_nullsafety: ^1.0.3
  pointycastle: ^4.0.0
  diffie_hellman: ^1.4.0
  crypto_keys_plus: ^0.5.0 # till cypto_keys lib is not updated

dev_dependencies:
  flutter:      # needed for flutter_nfc_kit
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_test: # needed for flutter_nfc_kit
    sdk: flutter
  lints: ^6.0.0
  test: ^1.26.3
